### ISSUE TITLE
[ Documentation ] Please, add Readme.

### ISSUE THREAD

**Issue by sudodoki** [patrick-steele-idem/browser-refresh-taglib#1]
It would be super awesome if we had readme in this module.

**Comment by patrick-steele-idem** [comment]
I'll see if I can put something together in the next day or two. However, there is some related documentation as part of the [browser-refresh](https://github.com/patrick-steele-idem/browser-refresh) module that describes how to use this taglib to inject the required code to allow the web browser page to refresh when a server-side file is modified. Please see:
https://github.com/patrick-steele-idem/browser-refresh#installation

**Comment by patrick-steele-idem** [comment]
Since we have a README.md file now I'm going to go ahead and close this issue. If you feel docs are still missing please let me know. Thanks.
