### ISSUE TITLE
Using base url instead of localhost

### ISSUE THREAD

**Issue by rtalwar26** [patrick-steele-idem/browser-refresh-taglib#2]
Its better to pickup base url from `window.location` rather than `localhost`.For example while using docker machines , a different ip address is assigned to the server.

**Comment by patrick-steele-idem** [comment]
I agree with you that using localhost is a problem. I'll see if I can push out a patch that is non-breaking.

**Comment by patrick-steele-idem** [comment]
New version published with improvement to use the hostname associated with the incoming request: `browser-refresh-taglib@1.1.0`

Please let me know if you see any issues with the new version. Thanks

**Comment by rtalwar26** [comment]
The url is now being populated according to host,  but i guess the main module [`browser-refresh.js`](https://github.com/patrick-steele-idem/browser-refresh) is still making requests to `localhost`

``` javascript
http://localhost:3999/socket.io/?EIO=3&transport=polling&t=LIP6sqP net::ERR_CONNECTION_REFUSED
```

**Comment by patrick-steele-idem** [comment]
You're right. The code needs to be tweaked a bit more. I will take a look

**Comment by patrick-steele-idem** [comment]
New version of `browser-refresh` published with fix to use window.location.hostname: `browser-refresh@1.6.0`
